// Kana Sprint canonical runtime.
// All behavior lives here. Files under data/ are behavior-free content modules.

const {kana:KANA,dakuten:DAKUTEN,youon:YOUON,confusables:CONF,vocab:VOCAB,chunks:CHUNKS,scenes:SCENES,patterns:PATTERNS,kanji:KANJI_WORDS}=window.KanaData;
const STORAGE_KEY='kanaSprintState';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toLocaleDateString('en-CA');

function loadState(){
  let saved={};try{saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{}}catch(e){saved={}}
  const s={xp:0,streak:0,lastDate:null,doneToday:0,items:{},sessions:0,lastOpen:null,studyHistory:[],recentQuestionKeys:[],settings:{romajiMode:'auto'},...saved};
  s.items=s.items||{};s.studyHistory=Array.isArray(s.studyHistory)?s.studyHistory:[];s.recentQuestionKeys=Array.isArray(s.recentQuestionKeys)?s.recentQuestionKeys:[];s.settings={romajiMode:'auto',...(s.settings||{})};
  if(s.lastDate&&!s.studyHistory.includes(s.lastDate))s.studyHistory.push(s.lastDate);return s;
}
let state=loadState(),queue=[],idx=0,correct=0,wrong=[],mode='daily',answered=false,romajiHidden=false;
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function itemStat(key){return state.items[key]||(state.items[key]={right:0,wrong:0,box:0,due:today()})}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function sample(a,n){return shuffle(a).slice(0,n)}
function distract(v,pool,n=3){return sample([...new Set(pool)].filter(x=>x!==v),n)}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id)?.classList.add('active');scrollTo(0,0)}
function qSignature(q){return q?.key||`${q?.type||''}:${q?.prompt||''}`}
function attemptsFor(st){return(st?.right||0)+(st?.wrong||0)}

function recentFactor(key){const recent=state.recentQuestionKeys||[],i=recent.lastIndexOf(key);if(i<0)return 1;const age=recent.length-1-i;if(age<12)return .08;if(age<28)return .28;if(age<55)return .62;return 1}
function reviewBoost(key){const st=state.items?.[key];if(!st)return 1;let b=1;if(st.due&&st.due<=today())b+=1.5;const a=attemptsFor(st);if(a)b+=Math.min(1.5,(st.wrong||0)/a*1.5);return b}
function weightedSample(items,n,weightFn){const pool=[...items],out=[];while(pool.length&&out.length<n){const weights=pool.map(x=>Math.max(.001,weightFn(x))),total=weights.reduce((a,b)=>a+b,0);let r=Math.random()*total,pick=0;for(let i=0;i<pool.length;i++){r-=weights[i];if(r<=0){pick=i;break}}out.push(pool.splice(pick,1)[0])}return out}
function vocabWeight(v){return(v.w||1.5)*recentFactor(v.j)*reviewBoost(v.j)}
const sceneKey=s=>'scene:'+s.ctx,chunkKey=c=>'chunk:'+c.j,kanjiKey=k=>'kanji:'+k.k,patternKey=p=>'pattern:'+p.key;

function spellingNote(j){const notes=[],dak={'ガ':'カ + ゛→ ガ (ga)','ギ':'キ + ゛→ ギ (gi)','グ':'ク + ゛→ グ (gu)','ゲ':'ケ + ゛→ ゲ (ge)','ゴ':'コ + ゛→ ゴ (go)','ザ':'サ + ゛→ ザ (za)','ジ':'シ + ゛→ ジ (ji)','ズ':'ス + ゛→ ズ (zu)','ゼ':'セ + ゛→ ゼ (ze)','ゾ':'ソ + ゛→ ゾ (zo)','ダ':'タ + ゛→ ダ (da)','デ':'テ + ゛→ デ (de)','ド':'ト + ゛→ ド (do)','バ':'ハ + ゛→ バ (ba)','ビ':'ヒ + ゛→ ビ (bi)','ブ':'フ + ゛→ ブ (bu)','ベ':'ヘ + ゛→ ベ (be)','ボ':'ホ + ゛→ ボ (bo)'},hand={'パ':'ハ + ゜→ パ (pa)','ピ':'ヒ + ゜→ ピ (pi)','プ':'フ + ゜→ プ (pu)','ペ':'ヘ + ゜→ ペ (pe)','ポ':'ホ + ゜→ ポ (po)'};for(const ch of j){if(dak[ch])notes.push('浊音：'+dak[ch]);if(hand[ch])notes.push('半浊音：'+hand[ch])}notes.push(...YOUON.filter(([x])=>j.includes(x)).map(([x,r])=>`拗音：${x} = ${r}`));if(j.includes('ッ'))notes.push('小ッ：让后面的辅音产生短促停顿/加倍');if(j.includes('ー'))notes.push('ー：把前一个元音拉长');return[...new Set(notes)].join('；')}

function kanaQ(entry=CONF[Math.floor(Math.random()*CONF.length)]){const[j,r,ds]=entry;return{key:j,type:'易混速辨',prompt:`「${j}」怎么读？`,sub:'训练第一眼反应。',answer:r,options:shuffle([r,...ds.map(d=>KANA.find(x=>x[0]===d)?.[1]||d)]),note:`易混组：${[j,...ds].join(' / ')}`}}
function vocabQ(v=weightedSample(VOCAB,1,vocabWeight)[0]){const reverse=Math.random()<.24,rule=spellingNote(v.j),note=`英文/来源：${v.src}${rule?'。'+rule:''}`;if(reverse)return{key:v.j,type:`${v.cat} · 反向识别`,prompt:`“${v.c}”是哪一个？`,sub:'从意思反推片假名。',answer:v.j,options:shuffle([v.j,...distract(v.j,VOCAB.map(x=>x.j))]),note,romaji:v.r};return{key:v.j,type:`${v.cat} · 外来语`,prompt:v.j,sub:'先直接判断日语里的实际意思。',answer:v.c,options:shuffle([v.c,...distract(v.c,VOCAB.map(x=>x.c))]),note,romaji:v.r}}

function boundaryPositions(chunks){let pos=0,out=[];chunks.slice(0,-1).forEach(c=>{pos+=Array.from(c).length;out.push(pos)});return out}
function formatSplit(chars,bounds){const b=[0,...[...bounds].sort((a,b)=>a-b),chars.length],parts=[];for(let i=0;i<b.length-1;i++)parts.push(chars.slice(b[i],b[i+1]).join(''));return parts.join('・')}
function chunkSplitOptions(c){const chars=Array.from(c.j),correctBounds=boundaryPositions(c.chunks),correct=formatSplit(chars,correctBounds),set=new Set([correct]);const add=b=>{const clean=[...new Set(b)].filter(x=>x>0&&x<chars.length).sort((a,b)=>a-b);if(clean.length)set.add(formatSplit(chars,clean))};correctBounds.forEach((p,i)=>[-1,1].forEach(d=>{const b=[...correctBounds];b[i]=p+d;add(b)}));for(let i=1;i<chars.length&&set.size<8;i++)add([i,...correctBounds.filter(x=>Math.abs(x-i)>1)]);for(let i=2;i<chars.length&&set.size<8;i+=2)add([i]);return shuffle([correct,...shuffle([...set].filter(x=>x!==correct)).slice(0,3)])}
function hasChunkFeature(c){return/[ッーャュョァィゥェォ]/.test(c.j)}
function chunkQ(c=weightedSample(CHUNKS,1,x=>recentFactor(chunkKey(x))*reviewBoost(chunkKey(x)))[0]){const split=c.chunks.join('・'),style=Math.random();if(hasChunkFeature(c)&&style<.46)return{key:chunkKey(c),type:'拆词阅读',prompt:c.j,sub:'四个选项都能拼回原词。选最利于保留小ッ、长音、拗音等声音块的推荐拆法。',answer:split,options:chunkSplitOptions(c),note:`推荐拆法：${split}。${c.tip} 意思：${c.c}。`,romaji:c.r};if(style<.74)return{key:chunkKey(c),type:'拆词阅读',prompt:split,sub:'按这些声音块快速读，整体是什么意思？',answer:c.c,options:shuffle([c.c,...distract(c.c,CHUNKS.map(x=>x.c))]),note:`${c.j} = ${c.c}。${c.tip}`,romaji:c.r};return{key:chunkKey(c),type:'拆词阅读',prompt:c.j,sub:`先在脑中按 ${split} 分块，再选最接近的读音。`,answer:c.r,options:shuffle([c.r,...distract(c.r,CHUNKS.map(x=>x.r))]),note:`推荐拆法：${split}。${c.tip} 意思：${c.c}。`}}
function sceneQ(s=weightedSample(SCENES,1,x=>recentFactor(sceneKey(x))*reviewBoost(sceneKey(x)))[0]){return{key:sceneKey(s),type:'真实场景',context:s.ctx,prompt:s.p,sub:'先读现场文字，再按实际语境回答。',answer:s.a,options:shuffle([s.a,...s.o]),note:s.note}}
function patternQ(p=PATTERNS[Math.floor(Math.random()*PATTERNS.length)]){return{...p,key:patternKey(p),options:shuffle(p.options),sub:'先认变化，再记规则。'}}
function kanjiQ(item=KANJI_WORDS[Math.floor(Math.random()*KANJI_WORDS.length)]){const askMeaning=Math.random()<.28;if(askMeaning)return{key:kanjiKey(item),type:'进阶 · 汉字实用词',prompt:item.k,sub:`${item.cat}场景：先在脑中读成片假名，再判断含义。`,answer:item.c,options:shuffle([item.c,...distract(item.c,KANJI_WORDS.map(x=>x.c))]),note:`${item.k} → ${item.y} → ${item.c}。`};return{key:kanjiKey(item),type:'进阶 · 汉字标音',prompt:`「${item.k}」怎么读？`,sub:'目前尚未学习平假名，所以统一使用片假名标音。',answer:item.y,options:shuffle([item.y,...distract(item.y,KANJI_WORDS.map(x=>x.y))]),note:`${item.k} → ${item.y}，意思是“${item.c}”。`}}
function speedQ(){const r=Math.random();return r<.22?kanaQ():r<.56?vocabQ():r<.76?chunkQ():r<.91?patternQ():sceneQ()}

function questionForKey(key){if(!key)return null;if(key.startsWith('scene:')){const s=SCENES.find(x=>sceneKey(x)===key);return s?sceneQ(s):null}if(key.startsWith('chunk:')){const c=CHUNKS.find(x=>chunkKey(x)===key);return c?chunkQ(c):null}if(key.startsWith('pattern:')){const p=PATTERNS.find(x=>patternKey(x)===key);return p?patternQ(p):null}if(key.startsWith('kanji:')){const k=KANJI_WORDS.find(x=>kanjiKey(x)===key);return k?kanjiQ(k):null}const v=VOCAB.find(x=>x.j===key);if(v)return vocabQ(v);const cf=CONF.find(x=>x[0]===key);return cf?kanaQ(cf):null}
function getReviewKeys(){const now=today();return Object.entries(state.items||{}).filter(([,s])=>(s.wrong||0)>0||(s.due&&s.due<=now)).sort((a,b)=>{const score=([,s])=>((s.due&&s.due<=now)?2:0)+(s.wrong||0)*.38+((s.wrong||0)/Math.max(1,attemptsFor(s)));return score(b)-score(a)}).map(([k])=>k)}
function uniqueQuestions(qs){const seen=new Set();return qs.filter(q=>{if(!q)return false;const k=qSignature(q);if(seen.has(k))return false;seen.add(k);return true})}
const weightedVocabs=n=>weightedSample(VOCAB,n,vocabWeight),weightedChunks=n=>weightedSample(CHUNKS,n,x=>recentFactor(chunkKey(x))*reviewBoost(chunkKey(x))),weightedScenes=n=>weightedSample(SCENES,n,x=>recentFactor(sceneKey(x))*reviewBoost(sceneKey(x))),weightedKanji=n=>weightedSample(KANJI_WORDS,n,x=>recentFactor(kanjiKey(x))*reviewBoost(kanjiKey(x)));
function buildQueue(m){mode=m;const target=m==='speed'?20:(m==='scene'?12:15);let q=[];if(m==='review'){q=getReviewKeys().map(questionForKey).filter(Boolean).slice(0,15);if(!q.length)q=[...sample(CONF,3).map(kanaQ),...weightedVocabs(4).map(vocabQ),...weightedChunks(2).map(chunkQ),...sample(PATTERNS,2).map(patternQ)];return uniqueQuestions(q).slice(0,15)}if(m==='confuse')q=sample(CONF,Math.min(8,CONF.length)).map(kanaQ);else if(m==='vocab')q=weightedVocabs(15).map(vocabQ);else if(m==='chunk')q=weightedChunks(15).map(chunkQ);else if(m==='pattern')q=sample(PATTERNS,15).map(patternQ);else if(m==='scene')q=weightedScenes(12).map(sceneQ);else if(m==='speed')q=Array.from({length:25},speedQ);else if(m==='kanji')q=weightedKanji(15).map(kanjiQ);else{const due=getReviewKeys().map(questionForKey).filter(Boolean).slice(0,3);q=[...due,...sample(CONF,3).map(kanaQ),...sample(PATTERNS,2).map(patternQ),...weightedVocabs(5).map(vocabQ),...weightedChunks(2).map(chunkQ),...weightedScenes(3).map(sceneQ)]}q=uniqueQuestions(q);let guard=0;while(q.length<target&&guard<80){const next=m==='confuse'?kanaQ():m==='vocab'?vocabQ():m==='chunk'?chunkQ():m==='pattern'?patternQ():m==='scene'?sceneQ():m==='kanji'?kanjiQ():speedQ();if(!q.some(x=>qSignature(x)===qSignature(next)))q.push(next);guard++}return shuffle(q).slice(0,target)}

function start(m='daily'){queue=buildQueue(m);idx=0;correct=0;wrong=[];show('quiz');renderQ()}
function sceneMeta(ctx=''){const rules=[[/机场|ゲート|チェックインカウンター|フライト|パスポート/,['AIRPORT','机场','air']],[/酒店|房间|前台|大堂|ランドリー|シャンプー|コンディショナー/,['HOTEL','酒店','hotel']],[/便利店|收银|商店|百货|礼品|药妆|支付|服装店|文具区/,['SHOP','商店 / 便利店','shop']],[/餐厅|咖啡|菜单|ドリンクバー/,['FOOD','餐厅 / 咖啡店','food']],[/地铁|站内|车站|ホーム/,['STATION','车站','station']],[/高速|租车|レンタカー/,['ROAD','道路 / 交通','road']],[/手机|网页|浏览器|アップデート|ログイン|アカウント|スクロール/,['SCREEN','手机 / 网页','screen']]];for(const[re,v]of rules)if(re.test(ctx))return v;return['SCENE','真实场景','generic']}
function splitSceneContext(ctx=''){const m=ctx.match(/^([^：:]{1,18})[：:]\s*(.+)$/);return m?{where:m[1],focus:m[2]}:{where:'',focus:ctx}}
function renderSceneCard(q){const box=$('#context');if(!box)return;box.className='context';box.innerHTML='';if(!q?.context)return;if(!String(q.type||'').includes('场景')){box.textContent=q.context;return}const[code,label,kind]=sceneMeta(q.context),{where,focus}=splitSceneContext(q.context);box.className='context scene-context scene-'+kind;box.innerHTML=`<div class="scene-topline"><span class="scene-mark">◉</span><span class="scene-label">${label}</span><span class="scene-code">${code}</span></div>${where?`<div class="scene-where">${where}</div>`:''}<div class="scene-focus">${focus}</div>`}
function rememberQuestion(q){const sig=qSignature(q);if(!sig)return;state.recentQuestionKeys=(state.recentQuestionKeys||[]).filter(x=>x!==sig);state.recentQuestionKeys.push(sig);state.recentQuestionKeys=state.recentQuestionKeys.slice(-80);save()}
function renderQ(){answered=false;const q=queue[idx];if(!q){finish();return}$('#qType').textContent=q.type;renderSceneCard(q);$('#prompt').textContent=q.prompt;$('#subprompt').textContent=q.sub||'';$('#quizCounter').textContent=`${idx+1}/${queue.length}`;$('#quizProgress').style.width=(idx/queue.length*100)+'%';$('#feedback').className='feedback hidden';$('#feedback').innerHTML='';$('#next').classList.add('hidden');$('#options').innerHTML='';q.options.forEach(o=>{const b=document.createElement('button');b.className='option';b.textContent=o;b.onclick=()=>answer(b,o,q);$('#options').appendChild(b)});rememberQuestion(q)}
function schedule(st,ok){if(ok){st.box=Math.min(5,(st.box||0)+1);const d=new Date();d.setDate(d.getDate()+[0,1,3,7,14,30][st.box]);st.due=d.toLocaleDateString('en-CA')}else{st.box=0;st.due=today()}}
function adaptiveRomajiVisible(q,ok){const setting=state.settings.romajiMode||'auto';if(!q.romaji)return false;if(setting==='always')return true;if(setting==='minimal')return !ok;if(!ok)return true;const st=state.items?.[q.key]||{right:0,wrong:0};if((state.sessions||0)<5||(st.right||0)<3)return true;return(st.right||0)/Math.max(1,attemptsFor(st))<.8}
function feedbackText(q,ok){const parts=[];if(adaptiveRomajiVisible(q,ok))parts.push(`读音：${q.romaji}`);if(q.note)parts.push(q.note);return parts.join(' ')}
function answer(btn,val,q){if(answered)return;answered=true;const ok=val===q.answer,st=itemStat(q.key);if(ok){correct++;st.right++;btn.classList.add('correct')}else{st.wrong++;wrong.push(q.key);btn.classList.add('wrong');$$('.option').find(x=>x.textContent===q.answer)?.classList.add('correct')}schedule(st,ok);$$('.option').forEach(x=>x.disabled=true);const f=$('#feedback');f.className='feedback '+(ok?'ok':'no');f.innerHTML=`<b>${ok?'✓ 很好':'✗ 正确答案：'+q.answer}</b><span>${feedbackText(q,ok)}</span>`;$('#next').classList.remove('hidden');save()}

function markStudyDay(){const t=today();if(!state.studyHistory.includes(t))state.studyHistory.push(t);state.studyHistory=state.studyHistory.sort().slice(-730);if(state.lastDate!==t){const y=new Date();y.setDate(y.getDate()-1);state.streak=state.lastDate===y.toLocaleDateString('en-CA')?(state.streak||0)+1:1;state.lastDate=t}}
function finish(){if(!queue.length){show('home');return}const pct=Math.round(correct/queue.length*100),earned=correct*7+(pct===100?25:0);state.xp=(state.xp||0)+earned;state.sessions=(state.sessions||0)+1;markStudyDay();if(mode==='daily')state.doneToday=Math.max(state.doneToday||0,queue.length);save();$('#scorePct').textContent=pct+'%';$('#earnedXp').textContent='+'+earned;$('#wrongCount').textContent=new Set(wrong).size;$('#resultTitle').textContent=pct>=90?'这一轮很稳':pct>=75?'不错，继续压缩反应时间':'薄弱项已经抓到了';$('#resultText').textContent=wrong.length?`这轮有 ${new Set(wrong).size} 个项目会被优先安排复习。`:'本轮全对，复习间隔会自动拉长。';show('result')}
function totalAttempts(){return Object.values(state.items||{}).reduce((n,s)=>n+attemptsFor(s),0)}function totalRight(){return Object.values(state.items||{}).reduce((n,s)=>n+(s.right||0),0)}function fmtDate(d){return d.toLocaleDateString('en-CA')}function startOfWeekMonday(base=new Date()){const d=new Date(base);d.setHours(12,0,0,0);const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d}function humanDate(d){return `${d.getMonth()+1}/${d.getDate()}`}
function friendlyWeakLabel(key){if(key.startsWith('chunk:'))return key.slice(6)+' · 拆词';if(key.startsWith('kanji:'))return key.slice(6)+' · 汉字';if(key.startsWith('pattern:'))return key.slice(8)+' · 规则';if(key.startsWith('scene:')){const raw=key.slice(6),focus=(raw.split(/[:：]/).slice(1).join('：')||raw).trim();return(focus.length>20?focus.slice(0,20)+'…':focus)+' · 场景'}return key}
function renderStudySummary(){const history=new Set(state.studyHistory||[]),attempts=totalAttempts(),rights=totalRight(),todayKey=today();$('#studyDays').textContent=history.size;$('#currentStreak').textContent=state.streak||0;$('#totalAnswers').textContent=attempts;$('#overallAccuracy').textContent=attempts?Math.round(rights/attempts*100)+'%':'—';const monday=startOfWeekMonday(),sunday=new Date(monday);sunday.setDate(monday.getDate()+6);$('#weekRange').textContent=`${humanDate(monday)} – ${humanDate(sunday)}`;const week=$('#weekCheckins');week.innerHTML='';for(let i=0;i<7;i++){const d=new Date(monday);d.setDate(monday.getDate()+i);const key=fmtDate(d),hit=history.has(key),isToday=key===todayKey,el=document.createElement('div'),timeClass=key<todayKey?'past':key>todayKey?'future':'';el.className=['day-dot',hit?'done':'',isToday?'today':'',timeClass].filter(Boolean).join(' ');el.setAttribute('aria-label',`${['周一','周二','周三','周四','周五','周六','周日'][i]} ${humanDate(d)}，${hit?'已学习':isToday?'今天，尚未学习':key<todayKey?'未打卡':'未来日期'}`);el.innerHTML=`<span>${['一','二','三','四','五','六','日'][i]}</span><b>${hit?'✓':d.getDate()}</b>`;week.appendChild(el)}$('#summaryNote').textContent=(state.streak||0)>=3?'连续学习正在形成':history.size?'保持轻量、持续就好':'从今天开始记录'}
function updateHome(){$('#xp').textContent=state.xp||0;$('#streak').textContent=state.streak||0;$('#dailyProgress').style.width=Math.min(100,(state.doneToday||0)/15*100)+'%';const attempts=totalAttempts(),rights=totalRight();$('#mastery').textContent=(attempts?Math.round(rights/attempts*100):0)+'%';const reviewKeys=getReviewKeys();$('#dueCount').textContent='复习 '+reviewKeys.filter(k=>state.items[k]?.due<=today()).length;$('#reviewBadge').textContent=reviewKeys.length;$('#reviewCopy').textContent=reviewKeys.length?`有 ${reviewKeys.length} 个错题/到期项目，优先从薄弱项开始`:'目前没有积压错题，可做预防性复习';const weak=Object.entries(state.items).filter(([,s])=>(s.wrong||0)>0).sort((a,b)=>((b[1].wrong+1)/(attemptsFor(b[1])+2))-((a[1].wrong+1)/(attemptsFor(a[1])+2))).slice(0,6).map(([k])=>friendlyWeakLabel(k));$('#weakList').innerHTML=(weak.length?weak:['シ / ツ','ソ / ン','ジ · 浊音','小ッ','拆词']).map(x=>`<span class="chip">${x}</span>`).join('');renderStudySummary()}
function renderCharts(){const rows=[['ア','イ','ウ','エ','オ'],['カ','キ','ク','ケ','コ'],['サ','シ','ス','セ','ソ'],['タ','チ','ツ','テ','ト'],['ナ','ニ','ヌ','ネ','ノ'],['ハ','ヒ','フ','ヘ','ホ'],['マ','ミ','ム','メ','モ'],['ヤ','','ユ','','ヨ'],['ラ','リ','ル','レ','ロ'],['ワ','','','','ヲ'],['ン','','','','']];$('#kanaChart').innerHTML=rows.flat().map(j=>{if(!j)return'<div class="kana-cell empty"></div>';const r=KANA.find(x=>x[0]===j)[1];return`<button class="kana-cell"><b>${j}</b><small>${r}</small></button>`}).join('');$('#dakutenChart').innerHTML=DAKUTEN.map(([j,r])=>`<span><b>${j}</b><small>${r}</small></span>`).join('');$('#youonChart').innerHTML=YOUON.map(([j,r])=>`<span><b>${j}</b><small>${r}</small></span>`).join('');$$('.kana-cell:not(.empty)').forEach(c=>c.onclick=()=>c.classList.toggle('hide-romaji'))}
function bindEvents(){$('#toggleRomaji').onclick=()=>{romajiHidden=!romajiHidden;$$('.kana-cell:not(.empty)').forEach(c=>c.classList.toggle('hide-romaji',romajiHidden));$('#toggleRomaji').textContent=romajiHidden?'显示全部读音':'隐藏全部读音'};$('#openChart').onclick=()=>{renderCharts();show('chart')};$('#closeChart').onclick=()=>show('home');$('#next').onclick=()=>{idx++;idx>=queue.length?finish():renderQ()};$('#startDaily').onclick=()=>start('daily');$$('.mode[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('#quit').onclick=()=>{show('home');updateHome()};$('#backHome').onclick=()=>{show('home');updateHome()};const select=$('#romajiMode');select.value=state.settings.romajiMode;select.onchange=()=>{state.settings.romajiMode=select.value;select.dataset.tone=select.value;save();const msg={auto:'自动模式：前期多显示；熟练项目答对后逐步隐藏；答错仍显示。',always:'始终显示：反馈保留罗马音，适合巩固阶段。',minimal:'尽量隐藏：答对时减少提示，答错时再显示。'};$('#romajiExplain').textContent=msg[select.value]};select.onchange()}
if(state.lastOpen!==today()){state.doneToday=0;state.lastOpen=today();save()}bindEvents();updateHome();
