// Expanded content pack 01 — practical katakana for daily life
VOCAB.push(
{j:'ミルク',r:'miruku',c:'牛奶',src:'milk',cat:'餐饮'},
{j:'パン',r:'pan',c:'面包',src:'葡萄牙语 pão',cat:'餐饮'},
{j:'トースト',r:'toosuto',c:'吐司',src:'toast',cat:'餐饮'},
{j:'サラダ',r:'sarada',c:'沙拉',src:'salad',cat:'餐饮'},
{j:'スープ',r:'suupu',c:'汤',src:'soup',cat:'餐饮'},
{j:'カレー',r:'karee',c:'咖喱',src:'curry',cat:'餐饮'},
{j:'パスタ',r:'pasuta',c:'意面',src:'pasta',cat:'餐饮'},
{j:'ピザ',r:'piza',c:'披萨',src:'pizza',cat:'餐饮'},
{j:'グラス',r:'gurasu',c:'玻璃杯',src:'glass',cat:'餐饮'},
{j:'カップ',r:'kappu',c:'杯子',src:'cup',cat:'餐饮'},
{j:'ストロー',r:'sut モロー'.replace(' モ','o'),c:'吸管',src:'straw',cat:'餐饮'},
{j:'フォーク',r:'fooku',c:'叉子',src:'fork',cat:'餐饮'},
{j:'スプーン',r:'supuun',c:'勺子',src:'spoon',cat:'餐饮'},
{j:'ナイフ',r:'naifu',c:'刀',src:'knife',cat:'餐饮'},
{j:'オーダー',r:'oodaa',c:'点单/订单',src:'order',cat:'餐饮'},
{j:'ドレッシング',r:'doresshingu',c:'沙拉酱',src:'dressing',cat:'餐饮'},
{j:'トッピング',r:'toppingu',c:'配料/加料',src:'topping',cat:'餐饮'},
{j:'ヨーグルト',r:'yooguruto',c:'酸奶',src:'yogurt',cat:'餐饮'},
{j:'プリン',r:'purin',c:'布丁',src:'pudding',cat:'餐饮'},
{j:'クッキー',r:'kukkii',c:'曲奇',src:'cookie',cat:'餐饮'},
{j:'パンケーキ',r:'pankeeki',c:'松饼/煎饼',src:'pancake',cat:'餐饮'},
{j:'シロップ',r:'shiroppu',c:'糖浆',src:'syrup',cat:'餐饮'},
{j:'ソフトクリーム',r:'sofuto kuriimu',c:'软冰淇淋',src:'soft cream（日式说法）',cat:'餐饮'},
{j:'ホットドッグ',r:'hotto doggu',c:'热狗',src:'hot dog',cat:'餐饮'},
{j:'ミネラルウォーター',r:'mineraru wootaa',c:'矿泉水',src:'mineral water',cat:'餐饮'},
{j:'ペットボトル',r:'petto botoru',c:'塑料饮料瓶',src:'PET bottle',cat:'购物'},
{j:'ビニール',r:'biniiru',c:'塑料/乙烯材质',src:'vinyl',cat:'购物'},
{j:'ビニール袋',r:'biniiru bukuro',c:'塑料袋',src:'vinyl + 袋',cat:'购物'},
{j:'セルフレジ',r:'serufu reji',c:'自助收银',src:'self register',cat:'购物'},
{j:'レシート',r:'reshiito',c:'小票/收据',src:'receipt',cat:'购物'},
{j:'バーコード',r:'baakoodo',c:'条形码',src:'barcode',cat:'购物'},
{j:'クーポン',r:'kuupon',c:'优惠券',src:'coupon',cat:'购物'},
{j:'ギフト',r:'gifuto',c:'礼物',src:'gift',cat:'购物'},
{j:'ラッピング',r:'rappingu',c:'包装/礼品包装',src:'wrapping',cat:'购物'},
{j:'ブランド',r:'burando',c:'品牌',src:'brand',cat:'购物'},
{j:'フロア',r:'furoa',c:'楼层',src:'floor',cat:'购物'},
{j:'エントランス',r:'entoransu',c:'入口/大堂入口',src:'entrance',cat:'旅行'},
{j:'ロビー',r:'robii',c:'大堂',src:'lobby',cat:'酒店'},
{j:'ルームキー',r:'ruumu kii',c:'房卡/房间钥匙',src:'room key',cat:'酒店'},
{j:'カードキー',r:'kaado kii',c:'卡片钥匙/房卡',src:'card key',cat:'酒店'},
{j:'モーニングコール',r:'mooningu kooru',c:'叫醒服务',src:'morning call（日式说法）',cat:'酒店'},
{j:'ランドリー',r:'randorii',c:'洗衣/洗衣房',src:'laundry',cat:'酒店'},
{j:'コインランドリー',r:'koin randorii',c:'自助投币洗衣房',src:'coin laundry',cat:'酒店'},
{j:'アメニティ',r:'ameniti',c:'酒店备品/洗护用品',src:'amenity',cat:'酒店'},
{j:'バスタオル',r:'basu taoru',c:'浴巾',src:'bath towel',cat:'酒店'},
{j:'フェイスタオル',r:'feisu taoru',c:'毛巾',src:'face towel',cat:'酒店'},
{j:'ドライヤー',r:'doraiyaa',c:'吹风机',src:'dryer',cat:'酒店'},
{j:'フリーWi-Fi',r:'furii waifai',c:'免费无线网络',src:'free Wi-Fi',cat:'酒店'},
{j:'パスワード',r:'pasuwaado',c:'密码',src:'password',cat:'科技'},
{j:'バッテリー',r:'batterii',c:'电池/电量',src:'battery',cat:'科技'},
{j:'チャージ',r:'chaaji',c:'充值/充电',src:'charge',cat:'科技'},
{j:'モバイルバッテリー',r:'mobairu batterii',c:'充电宝',src:'mobile battery',cat:'科技'},
{j:'イヤホン',r:'iyahon',c:'耳机',src:'earphone',cat:'科技'},
{j:'ヘッドホン',r:'heddohon',c:'头戴耳机',src:'headphone',cat:'科技'},
{j:'アプリ',r:'apuri',c:'应用程序',src:'application（缩略）',cat:'科技'},
{j:'ダウンロード',r:'daunroodo',c:'下载',src:'download',cat:'科技'},
{j:'アップデート',r:'appudeeto',c:'更新',src:'update',cat:'科技'},
{j:'ログイン',r:'roguin',c:'登录',src:'login',cat:'科技'},
{j:'ログアウト',r:'roguauto',c:'退出登录',src:'logout',cat:'科技'},
{j:'ネット',r:'netto',c:'网络/互联网',src:'internet（缩略）',cat:'科技'},
{j:'オンライン',r:'onrain',c:'在线',src:'online',cat:'科技'},
{j:'オフライン',r:'ofurain',c:'离线',src:'offline',cat:'科技'},
{j:'ホームページ',r:'hoomu peeji',c:'网站主页',src:'homepage',cat:'科技'},
{j:'メール',r:'meeru',c:'邮件',src:'mail',cat:'科技'},
{j:'メッセージ',r:'messeeji',c:'消息',src:'message',cat:'科技'},
{j:'スクリーン',r:'sukuriin',c:'屏幕',src:'screen',cat:'科技'},
{j:'コピー',r:'kopii',c:'复印/复制',src:'copy',cat:'科技'},
{j:'プリンター',r:'purintaa',c:'打印机',src:'printer',cat:'科技'},
{j:'データ',r:'deeta',c:'数据',src:'data',cat:'科技'},
{j:'ファイル',r:'fairu',c:'文件',src:'file',cat:'科技'},
{j:'フォルダー',r:'forudaa',c:'文件夹',src:'folder',cat:'科技'},
{j:'ターミナル',r:'taaminaru',c:'航站楼/终点站',src:'terminal',cat:'交通'},
{j:'ゲート',r:'geeto',c:'登机口/闸门',src:'gate',cat:'交通'},
{j:'カウンター',r:'kauntaa',c:'柜台',src:'counter',cat:'交通'},
{j:'チェックインカウンター',r:'chekkuin kauntaa',c:'值机柜台',src:'check-in counter',cat:'交通'},
{j:'シャトルバス',r:'shatoru basu',c:'接驳巴士',src:'shuttle bus',cat:'交通'},
{j:'レンタカー',r:'rentakaa',c:'租车',src:'rent-a-car',cat:'交通'},
{j:'パーキング',r:'paakingu',c:'停车场/停车',src:'parking',cat:'交通'},
{j:'サービスエリア',r:'saabisu eria',c:'高速公路服务区',src:'service area',cat:'交通'},
{j:'インターチェンジ',r:'intaachenji',c:'高速互通/出入口',src:'interchange',cat:'交通'},
{j:'ナビ',r:'nabi',c:'导航',src:'navigation（缩略）',cat:'交通'},
{j:'マップ',r:'mappu',c:'地图',src:'map',cat:'交通'}
);

CHUNKS.push(
{j:'モバイルバッテリー',chunks:['モバイル','バッ','テ','リー'],r:'mobairu · bat · te · rii',c:'充电宝',tip:'バッテリー里小ッ形成 tt，リー有长音。'},
{j:'チェックインカウンター',chunks:['チェックイン','カウン','ター'],r:'chekkuin · kaun · taa',c:'值机柜台',tip:'先把熟悉的 チェックイン 当成整体，再读后面的 カウンター。'},
{j:'コインランドリー',chunks:['コイン','ラン','ド','リー'],r:'koin · ran · do · rii',c:'自助投币洗衣房',tip:'コイン + ランドリー，是很典型的组合词。'},
{j:'モーニングコール',chunks:['モー','ニング','コー','ル'],r:'moo · ningu · koo · ru',c:'叫醒服务',tip:'两个 ー 都是长音；这是酒店里常见的日式英语。'},
{j:'サービスエリア',chunks:['サー','ビス','エ','リア'],r:'saa · bisu · e · ria',c:'高速公路服务区',tip:'サービス + エリア，看到熟悉词块会快很多。'},
{j:'インターチェンジ',chunks:['イン','ター','チェン','ジ'],r:'in · taa · chen · ji',c:'高速互通/出入口',tip:'チェンジ = change；ジ 是浊音。'},
{j:'ミネラルウォーター',chunks:['ミネラル','ウォー','ター'],r:'mineraru · woo · taa',c:'矿泉水',tip:'ウォーター里有 ウォ 和两个长音。'},
{j:'ソフトクリーム',chunks:['ソフト','クリー','ム'],r:'sofuto · kurii · mu',c:'软冰淇淋',tip:'ソフト + クリーム；日本很常见的说法。'},
{j:'ペットボトル',chunks:['ペッ','ト','ボ','トル'],r:'pet · to · bo · toru',c:'塑料饮料瓶',tip:'ペット里的小ッ让 t 加倍。'},
{j:'セルフレジ',chunks:['セルフ','レジ'],r:'serufu · reji',c:'自助收银',tip:'先抓 セルフ = self，再认 レジ = 收银台。'},
{j:'ルームキー',chunks:['ルー','ム','キー'],r:'ruu · mu · kii',c:'房卡/房间钥匙',tip:'两个长音都很明显。'},
{j:'ダウンロード',chunks:['ダウン','ロー','ド'],r:'daun · roo · do',c:'下载',tip:'ロー中的 ー 拉长 o。'},
{j:'アップデート',chunks:['アッ','プ','デー','ト'],r:'ap · pu · dee · to',c:'更新',tip:'小ッ形成 pp，デー有长音。'},
{j:'ホームページ',chunks:['ホーム','ペー','ジ'],r:'hoomu · pee · ji',c:'网站主页',tip:'ホーム 和 ページ 都可以作为熟悉词块记。'},
{j:'チェックインカウンター',chunks:['チェック','イン','カウン','ター'],r:'chekku · in · kaun · taa',c:'值机柜台',tip:'先认 チェックイン，再接 カウンター。'}
);

SCENES.push(
{ctx:'便利店收银台：セルフレジ',p:'这里最可能是什么？',a:'自助收银台',o:['人工问讯台','行李寄存柜','自动售票机'],note:'セルフ = self；レジ = register/收银台。'},
{ctx:'便利店店员：レシートはご利用ですか？',p:'店员在问你要不要什么？',a:'小票/收据',o:['塑料袋','优惠券','积分卡'],note:'レシート = receipt。'},
{ctx:'商店标签：クーポン利用可',p:'这表示什么？',a:'可以使用优惠券',o:['可以退税','可以预约','可以寄存'],note:'クーポン = coupon。'},
{ctx:'酒店房间：ドライヤー',p:'最可能指什么用品？',a:'吹风机',o:['空调遥控器','烧水壶','加湿器'],note:'ドライヤー = dryer。'},
{ctx:'酒店：コインランドリー 3F',p:'三楼有什么？',a:'自助投币洗衣房',o:['早餐厅','公共浴场','健身房'],note:'コイン + ランドリー。'},
{ctx:'酒店前台：モーニングコール',p:'这是哪项服务？',a:'叫醒服务',o:['早餐券','客房清扫','机场接送'],note:'日本酒店里常用 モーニングコール 表示 wake-up call。'},
{ctx:'房间说明：フリーWi-Fi',p:'这通常表示什么？',a:'提供免费无线网络',o:['提供免费电视','提供免费电话','提供免费早餐'],note:'フリー = free；Wi-Fi 直接读作 waifai。'},
{ctx:'机场：チェックインカウンター',p:'应该去这里做什么？',a:'办理值机',o:['领取行李','过海关','退税'],note:'チェックイン + カウンター。'},
{ctx:'机场：ゲート 52',p:'这里的「ゲート」最可能是什么？',a:'登机口',o:['行李转盘','售票柜台','停车场'],note:'ゲート = gate。'},
{ctx:'机场交通：シャトルバス',p:'最可能是什么车？',a:'接驳巴士',o:['出租车','高速列车','观光船'],note:'シャトルバス = shuttle bus。'},
{ctx:'租车柜台：レンタカー',p:'这里提供什么服务？',a:'租车',o:['修车','洗车','卖车票'],note:'レンタカー = rent-a-car。'},
{ctx:'高速公路：サービスエリア',p:'你最可能在哪里看到这个词？',a:'高速公路服务区',o:['酒店前台','地铁站台','百货商场'],note:'日本高速公路常见 サービスエリア。'},
{ctx:'手机：アップデートがあります',p:'大意是什么？',a:'有可用更新',o:['电量不足','没有网络','需要登录'],note:'アップデート = update。'},
{ctx:'网页：ログインしてください',p:'页面要求你做什么？',a:'登录',o:['下载','打印','退出'],note:'ログイン = login。'},
{ctx:'手机：バッテリー 10%',p:'这表示什么？',a:'电量只剩 10%',o:['网速 10%','音量 10%','存储空间 10%'],note:'バッテリー = battery。'},
{ctx:'店内指示：エントランス',p:'这个词最可能指哪里？',a:'入口',o:['出口','收银台','电梯'],note:'エントランス = entrance。'},
{ctx:'百货店：フロアガイド',p:'这最可能是什么？',a:'楼层指南',o:['商品折扣','餐厅菜单','停车票'],note:'フロア = floor；ガイド = guide。'},
{ctx:'礼品柜台：ラッピング',p:'这里可以提供什么？',a:'礼品包装',o:['积分兑换','快递寄送','退税'],note:'ラッピング = wrapping。'},
{ctx:'饮料区：ペットボトル',p:'这里说的「ペット」不是宠物，而是？',a:'PET 塑料饮料瓶',o:['宠物饮用水','玻璃瓶','纸盒'],note:'ペットボトル = PET bottle。'},
{ctx:'餐厅：トッピング追加',p:'这通常是什么意思？',a:'可以追加配料',o:['可以打包','可以换座位','可以预约'],note:'トッピング = topping；追加 = 加上/追加。'}
);

PATTERNS.push(
{key:'フォ',type:'外来音',prompt:'「フォ」通常怎么读？',answer:'fo',options:['fo','ho','fu','wo'],note:'フ + 小ォ → フォ (fo)，常见于 フォーク、フォルダー。'},
{key:'ウォ',type:'外来音',prompt:'「ウォ」通常怎么读？',answer:'wo',options:['wo','uo','o','wa'],note:'ウ + 小ォ → ウォ，常见于 ウォーター。'},
{key:'ティ',type:'外来音',prompt:'「ティ」通常怎么读？',answer:'ti',options:['ti','chi','te','di'],note:'テ + 小ィ → ティ，用来表示更接近外语的 ti 音。'},
{key:'ファ',type:'外来音',prompt:'「ファ」通常怎么读？',answer:'fa',options:['fa','ha','fua','pa'],note:'フ + 小ァ → ファ，常见于 ファイル。'},
{key:'チェ',type:'外来音',prompt:'「チェ」通常怎么读？',answer:'che',options:['che','chi','she','je'],note:'チ + 小ェ → チェ，常见于 チェック。'},
{key:'ディ',type:'外来音',prompt:'「ディ」通常怎么读？',answer:'di',options:['di','ji','de','ti'],note:'デ + 小ィ → ディ，用来表示外来语的 di。'}
);
