// Content pack 02 — broader practical katakana coverage.
// Data only. Do not put runtime behavior in content packs.

VOCAB.push(
{j:'アイス',r:'aisu',c:'冰的/冰品',src:'ice',cat:'餐饮',w:3},
{j:'ホット',r:'hotto',c:'热的/热饮',src:'hot',cat:'餐饮',w:3},
{j:'コーラ',r:'koora',c:'可乐',src:'cola',cat:'餐饮',w:2},
{j:'ワイン',r:'wain',c:'葡萄酒',src:'wine',cat:'餐饮',w:2},
{j:'ハム',r:'hamu',c:'火腿',src:'ham',cat:'餐饮',w:2},
{j:'ベーコン',r:'beekon',c:'培根',src:'bacon',cat:'餐饮',w:2},
{j:'ソーセージ',r:'sooseeji',c:'香肠',src:'sausage',cat:'餐饮',w:2},
{j:'ステーキ',r:'suteeki',c:'牛排/肉排',src:'steak',cat:'餐饮',w:2},
{j:'ハンバーグ',r:'hanbaagu',c:'日式汉堡肉排',src:'hamburg steak',cat:'餐饮',w:2},
{j:'オムライス',r:'omuraisu',c:'蛋包饭',src:'omelet + rice（日式造词）',cat:'餐饮',w:2},
{j:'グラタン',r:'guratan',c:'焗烤/奶油焗菜',src:'gratin',cat:'餐饮',w:1},
{j:'ドーナツ',r:'doonatsu',c:'甜甜圈',src:'doughnut',cat:'餐饮',w:2},
{j:'アイスクリーム',r:'aisukuriimu',c:'冰淇淋',src:'ice cream',cat:'餐饮',w:3},
{j:'ジェラート',r:'jeraato',c:'意式冰淇淋',src:'gelato',cat:'餐饮',w:1},
{j:'マヨネーズ',r:'mayoneezu',c:'蛋黄酱',src:'mayonnaise',cat:'餐饮',w:2},
{j:'ケチャップ',r:'kechappu',c:'番茄酱',src:'ketchup',cat:'餐饮',w:2},
{j:'ソース',r:'soosu',c:'酱汁',src:'sauce',cat:'餐饮',w:2},
{j:'ドリンクバー',r:'dorinku baa',c:'自助饮料吧',src:'drink bar（日式用法）',cat:'餐饮',w:2},
{j:'テーブル',r:'teeburu',c:'桌子/餐桌',src:'table',cat:'生活',w:3},
{j:'カフェ',r:'kafe',c:'咖啡馆',src:'café',cat:'餐饮',w:3},
{j:'サイズ',r:'saizu',c:'尺寸/尺码',src:'size',cat:'购物',w:3},
{j:'セール',r:'seeru',c:'促销/打折',src:'sale',cat:'购物',w:3},
{j:'バーゲン',r:'baagen',c:'大减价/特卖',src:'bargain',cat:'购物',w:1},
{j:'ショップ',r:'shoppu',c:'商店',src:'shop',cat:'购物',w:2},
{j:'デパート',r:'depaato',c:'百货商场',src:'department store（缩略）',cat:'购物',w:3},
{j:'ドラッグストア',r:'doraggu sutoa',c:'药妆店/药店',src:'drugstore',cat:'购物',w:3},
{j:'エコバッグ',r:'eko baggu',c:'环保购物袋',src:'eco bag',cat:'购物',w:2},
{j:'キャッシュレス',r:'kyasshuresu',c:'无现金支付',src:'cashless',cat:'购物',w:2},
{j:'デビットカード',r:'debitto kaado',c:'借记卡',src:'debit card',cat:'购物',w:2},
{j:'レンタル',r:'rentaru',c:'租赁/出租',src:'rental',cat:'购物',w:2},
{j:'シングル',r:'shinguru',c:'单人房/单人',src:'single',cat:'酒店',w:2},
{j:'ツイン',r:'tsuin',c:'双床房/双床',src:'twin',cat:'酒店',w:2},
{j:'ルーム',r:'ruumu',c:'房间',src:'room',cat:'酒店',w:2},
{j:'バスルーム',r:'basu ruumu',c:'浴室',src:'bathroom',cat:'酒店',w:2},
{j:'シャンプー',r:'shanpuu',c:'洗发水',src:'shampoo',cat:'酒店',w:3},
{j:'コンディショナー',r:'kondishonaa',c:'护发素',src:'conditioner',cat:'酒店',w:2},
{j:'ボディソープ',r:'bodi soopu',c:'沐浴露',src:'body soap',cat:'酒店',w:2},
{j:'パジャマ',r:'pajama',c:'睡衣',src:'pajamas',cat:'酒店',w:2},
{j:'スーツケース',r:'suutsu keesu',c:'行李箱',src:'suitcase',cat:'旅行',w:3},
{j:'キャリーケース',r:'kyarii keesu',c:'拉杆箱',src:'carry case（日式常用说法）',cat:'旅行',w:2},
{j:'リュック',r:'ryukku',c:'双肩包',src:'Rucksack（德语来源）',cat:'旅行',w:2},
{j:'パスポート',r:'pasupooto',c:'护照',src:'passport',cat:'旅行',w:3},
{j:'ビザ',r:'biza',c:'签证',src:'visa',cat:'旅行',w:2},
{j:'フライト',r:'furaito',c:'航班',src:'flight',cat:'交通',w:3},
{j:'トランジット',r:'toranjitto',c:'中转/过境',src:'transit',cat:'交通',w:1},
{j:'レンタサイクル',r:'renta saikuru',c:'自行车租赁',src:'rental + cycle（日式缩略）',cat:'交通',w:1},
{j:'アカウント',r:'akaunto',c:'账户',src:'account',cat:'科技',w:3},
{j:'パスコード',r:'pasukoodo',c:'密码/解锁码',src:'passcode',cat:'科技',w:2},
{j:'ネットワーク',r:'nettowaaku',c:'网络',src:'network',cat:'科技',w:2},
{j:'ブラウザ',r:'burauza',c:'浏览器',src:'browser',cat:'科技',w:2},
{j:'サイト',r:'saito',c:'网站/站点',src:'site',cat:'科技',w:3},
{j:'チャット',r:'chatto',c:'聊天',src:'chat',cat:'科技',w:3},
{j:'ビデオ',r:'bideo',c:'视频',src:'video',cat:'科技',w:2},
{j:'ボタン',r:'botan',c:'按钮',src:'button',cat:'科技',w:3},
{j:'スクロール',r:'sukurooru',c:'滚动页面',src:'scroll',cat:'科技',w:2},
{j:'タブ',r:'tabu',c:'标签页',src:'tab',cat:'科技',w:2},
{j:'ティッシュ',r:'tisshu',c:'纸巾',src:'tissue',cat:'生活',w:3},
{j:'マスク',r:'masuku',c:'口罩/面罩',src:'mask',cat:'生活',w:3},
{j:'トイレットペーパー',r:'toiretto peepaa',c:'卫生纸',src:'toilet paper',cat:'生活',w:2},
{j:'キッチン',r:'kicchin',c:'厨房',src:'kitchen',cat:'生活',w:3},
{j:'ドア',r:'doa',c:'门',src:'door',cat:'生活',w:3},
{j:'カーテン',r:'kaaten',c:'窗帘',src:'curtain',cat:'生活',w:2},
{j:'ソファ',r:'sofa',c:'沙发',src:'sofa',cat:'生活',w:2},
{j:'クッション',r:'kusshon',c:'靠垫/软垫',src:'cushion',cat:'生活',w:2},
{j:'ノート',r:'nooto',c:'笔记本',src:'note / notebook',cat:'学习',w:3},
{j:'ペン',r:'pen',c:'笔',src:'pen',cat:'学习',w:3},
{j:'ボールペン',r:'boorupen',c:'圆珠笔',src:'ballpoint pen（日式缩略）',cat:'学习',w:3},
{j:'スケジュール',r:'sukejuuru',c:'日程/计划',src:'schedule',cat:'学习',w:3},
{j:'ミーティング',r:'miitingu',c:'会议',src:'meeting',cat:'学习',w:2},
{j:'メモ',r:'memo',c:'便签/记录',src:'memo',cat:'学习',w:3},
{j:'シャツ',r:'shatsu',c:'衬衫',src:'shirt',cat:'服饰',w:3},
{j:'ジャケット',r:'jaketto',c:'夹克/西装外套',src:'jacket',cat:'服饰',w:2},
{j:'コート',r:'kooto',c:'大衣',src:'coat',cat:'服饰',w:2},
{j:'セーター',r:'seetaa',c:'毛衣',src:'sweater',cat:'服饰',w:2},
{j:'スカート',r:'sukaato',c:'裙子',src:'skirt',cat:'服饰',w:2},
{j:'ワンピース',r:'wanpiisu',c:'连衣裙',src:'one-piece（日式用法）',cat:'服饰',w:2},
{j:'ジーンズ',r:'jiinzu',c:'牛仔裤',src:'jeans',cat:'服饰',w:2},
{j:'スニーカー',r:'suniikaa',c:'运动鞋',src:'sneakers',cat:'服饰',w:2},
{j:'サンダル',r:'sandaru',c:'凉鞋/拖鞋',src:'sandals',cat:'服饰',w:2},
{j:'バッグ',r:'baggu',c:'包/袋',src:'bag',cat:'服饰',w:3}
);

CHUNKS.push(
{j:'ドラッグストア',chunks:['ドラッ','グ','スト','ア'],r:'dorag · gu · suto · a',c:'药妆店/药店',tip:'ドラッグ里的小ッ让 g 前出现短促停顿。'},
{j:'キャッシュレス',chunks:['キャッ','シュ','レ','ス'],r:'kyas · shu · re · su',c:'无现金支付',tip:'キャ 是拗音；小ッ让后面的 sh 更短促。'},
{j:'デビットカード',chunks:['デ','ビッ','ト','カー','ド'],r:'de · bit · to · kaa · do',c:'借记卡',tip:'ビット中小ッ形成 tt；カード有长音。'},
{j:'コンディショナー',chunks:['コン','ディ','ショ','ナー'],r:'kon · di · sho · naa',c:'护发素',tip:'ディ 是外来音；ショ 是拗音；ナー有长音。'},
{j:'スーツケース',chunks:['スー','ツ','ケー','ス'],r:'suu · tsu · kee · su',c:'行李箱',tip:'スー、ケー都有长音。'},
{j:'キャリーケース',chunks:['キャ','リー','ケー','ス'],r:'kya · rii · kee · su',c:'拉杆箱',tip:'キャ 是拗音；リー、ケー有长音。'},
{j:'パスポート',chunks:['パス','ポー','ト'],r:'pasu · poo · to',c:'护照',tip:'ポー里的 ー 把 o 拉长。'},
{j:'トランジット',chunks:['トラン','ジッ','ト'],r:'toran · jit · to',c:'中转/过境',tip:'ジ 是浊音；ジット里的小ッ强化 t。'},
{j:'ネットワーク',chunks:['ネッ','ト','ワー','ク'],r:'net · to · waa · ku',c:'网络',tip:'ネット有小ッ；ワー有长音。'},
{j:'スクロール',chunks:['スク','ロー','ル'],r:'suku · roo · ru',c:'滚动页面',tip:'ロー里的 ー 拉长 o。'},
{j:'トイレットペーパー',chunks:['トイ','レッ','ト','ペー','パー'],r:'toi · ret · to · pee · paa',c:'卫生纸',tip:'レッ有小ッ，ペー和パー都有长音。'},
{j:'スケジュール',chunks:['スケ','ジュー','ル'],r:'suke · juu · ru',c:'日程/计划',tip:'ジュー含ジュ拗音和长音。'},
{j:'ミーティング',chunks:['ミー','ティン','グ'],r:'mii · tin · gu',c:'会议',tip:'ティ是外来音；ミー有长音。'},
{j:'ボールペン',chunks:['ボー','ル','ペン'],r:'boo · ru · pen',c:'圆珠笔',tip:'ボー里的长音要拉长。'},
{j:'ジャケット',chunks:['ジャ','ケッ','ト'],r:'ja · ket · to',c:'夹克/外套',tip:'ジャ是拗音；ケット有小ッ。'},
{j:'ワンピース',chunks:['ワン','ピー','ス'],r:'wan · pii · su',c:'连衣裙',tip:'ピー有长音；日语里的ワンピース通常指连衣裙。'},
{j:'スニーカー',chunks:['ス','ニー','カー'],r:'su · nii · kaa',c:'运动鞋',tip:'ニー和カー都有长音。'},
{j:'アイスクリーム',chunks:['アイス','クリー','ム'],r:'aisu · kurii · mu',c:'冰淇淋',tip:'クリーム里的リー有长音。'},
{j:'ソーセージ',chunks:['ソー','セー','ジ'],r:'soo · see · ji',c:'香肠',tip:'两个长音后面接浊音ジ。'},
{j:'ドリンクバー',chunks:['ドリン','ク','バー'],r:'dorin · ku · baa',c:'自助饮料吧',tip:'バー有长音，日本餐厅里常见。'}
);

SCENES.push(
{ctx:'餐厅入口：ドリンクバー',p:'这个区域最可能提供什么？',a:'自助饮料',o:['寄存行李','自助结账','租借雨伞'],note:'ドリンクバー = drink bar，常指可自助续取的饮料区。'},
{ctx:'商店海报：セール 30% OFF',p:'最合理的理解是？',a:'正在打折促销',o:['只收现金','商品已售罄','需要预约'],note:'セール = sale。看到 OFF 通常就是折扣。'},
{ctx:'药妆店招牌：ドラッグストア',p:'这是什么类型的店？',a:'药妆店/药店',o:['百货商场','咖啡馆','便利店'],note:'ドラッグストア = drugstore。'},
{ctx:'支付提示：キャッシュレス',p:'这通常表示什么？',a:'支持或强调无现金支付',o:['只接受现金','暂停营业','免税'],note:'キャッシュレス = cashless。'},
{ctx:'酒店房型：シングル / ツイン',p:'「ツイン」通常指？',a:'双床房',o:['单人房','套房','吸烟房'],note:'ツイン = twin；酒店语境通常指两张床。'},
{ctx:'酒店浴室：シャンプー / コンディショナー / ボディソープ',p:'「コンディショナー」是什么？',a:'护发素',o:['洗发水','沐浴露','洗面奶'],note:'コンディショナー = conditioner。'},
{ctx:'机场出发屏：フライト UA838',p:'「フライト」指什么？',a:'航班',o:['登机口','行李箱','签证'],note:'フライト = flight。'},
{ctx:'机场柜台：パスポートをお願いします',p:'工作人员在要什么？',a:'护照',o:['登机牌','信用卡','行李票'],note:'パスポート = passport。'},
{ctx:'手机登录：アカウント',p:'这个词通常指什么？',a:'账户',o:['密码','网络','浏览器'],note:'アカウント = account。'},
{ctx:'网页提示：スクロールしてください',p:'页面要求你做什么？',a:'向下/上下滚动页面',o:['登录','刷新页面','下载文件'],note:'スクロール = scroll。'},
{ctx:'浏览器界面：新しいタブ',p:'「タブ」最可能指？',a:'标签页',o:['按钮','文件夹','密码'],note:'タブ = tab。'},
{ctx:'酒店房间：ティッシュ',p:'这是什么日用品？',a:'纸巾',o:['毛巾','拖鞋','枕头'],note:'ティッシュ = tissue。'},
{ctx:'房间设备：カーテン',p:'这个词指什么？',a:'窗帘',o:['地毯','床单','门'],note:'カーテン = curtain。'},
{ctx:'文具区：ボールペン',p:'这是什么？',a:'圆珠笔',o:['铅笔','记号笔','笔记本'],note:'ボールペン是日语里非常常见的“圆珠笔”说法。'},
{ctx:'服装店：サイズ M / L',p:'「サイズ」表示什么？',a:'尺码/尺寸',o:['价格','颜色','材质'],note:'サイズ = size。'}
);
